### PR TITLE
generic projections by well known text(transversal mercator ...)

### PR DESCRIPTION
**Pull request by RichyP7**
Hello
You said you would like to have a look at my implementation details of the transversal Mercator projection. I built a generic WKT projection which can use **Well known text** (f.e. by epsg.io) to produce a lot more projections. I did successfully implement it and test it with an wms layer (and server) which used austral lambert and another one with gauss Krueger.
 I added an extension to wpf.mapcontrol with the use of a dependency to proj4netgeoapi!
Maybe you don´t like to have the new dependencies in your project. I separated  it to a projection extension but maybe that´s not in your interest.
If not maybe you allow me to build an extension project for your library. Your work is magnificent. Thank you

### CODE REVIEW

**Comment by ClemensFischer** [comment]
Hi, I'll have a look at it in your fork. I do generally not accept pull requests. Not sure what an extension project exactly is.

**Comment by RichyP7** [comment]
Okay no problem. I meant just an extension library(for extending the functions of yours) to your existing. I wasn't able to build it with the referrencing of the uwp things but should be no problem for you. (Sorry I don't know much about  uwp)

**Comment by ClemensFischer** [comment]
Well, it's open source, so go ahead.

**Comment by ClemensFischer** [comment]
Hi Richy, please take a look at the last commit. I've added a MapProjections library with a GeoApiProjection class based on ProjNET4GeoApi. You can either set its CoordinateTransform or Wkt property. There's also a UtmProjection class derived from it, which has a ZoneName property.

**Comment by RichyP7** [comment]
That was my intention. I like your work. Keep going . Thank you :) 👍

**Pull request closed without merging**
